version: '3'

services:
  street-drop-api-server:
    image: yunyoung18190/street-drop-api-server:latest
    container_name: street-drop-api-server
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - 8080:8080