global:
  scrape_interval: 15s
  evaluation_interval: 1m
  external_labels:
    monitor: 'street drop monitor'
scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']