management:
  endpoints:
    web:
      exposure:
        include: prometheus
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
    database-platform: org.hibernate.dialect.MySQLDialect

cloud:
  aws:
    credentials:
      accessKey: fakeValue
      secretKey: fakeValue
    s3:
      bucket: street-drop
      region:
        auto: false
        static: ap-northeast-2
      stack:
        auto: false