spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    baseline-on-migrate: true
    ignore-migration-patterns: "*:missing"
auth:
  header: ${AUTH_HEADER}
  secret-key: ${AUTH_SECRET_KEY}
fcm:
  value: streetdrop-notification-fcm.json