management:
  endpoints:
    web:
      exposure:
        include: prometheus
logging:
  level:
    root: INFO
    org.springframework.web: INFO
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true