version: "3.9"

services:
  admin-server:
    container_name: street-drop-admin-server
    build:
      context: ./streetdrop-admin-server
      dockerfile: Dockerfile
    ports:
      - "3000:8080"

  web-server:
    container_name: street-drop-admin-web-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:3030"

  mongodb:
    image: mongo
    container_name: street-drop-admin-mongodb
    ports:
      - "27017:27017"
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: rootpassword