version: '3'
services:
  redis:
    image: redis
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"

  street-drop-server-api:
    image: street-drop-server-api
    container_name: street-drop-server-api
    build:
      context: ''
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - redis

