name: Docs

on:
  push:
    branches: [main, dev, config/docs]
    paths:
      - "docs/**"
  pull_request:
    branches: [main, dev, config/docs]
    paths:
      - "docs/**"

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build docs
        run: |
          cd docs
          yarn install
          yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          user_name: github-actions[bot]
          user_email: 41898282+github-actionㅅs[bot]@users.noreply.github.com