# STREET-DROP GIT ACTION 
name: Street Drop Server Git Action

# main push 작업 일어나면 git action 실행
on:
  push:
    branches: [ "config/deploy" ]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    # Set JDK Version
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        
    # Modify Permission
    - name: Grant Execute Permission For Gradlew
      run: chmod +x gradlew
    
    # Build Gradle
    - name: Build with Gradle
      run: ./gradlew clean build --exclude-task test
      
    # Login DockerHub
    - name: Login To DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
    # Build Docker Container
    - name: Docker Image Build And Push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: street-drop-api:prod
        build-args: STAGE=prod
      
      
    
